name: CI/CD for dataflow-builder

on: [push, pull_request]

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build project (Release)
        run: dotnet build -c Release
      - name: Run tests (Release)
        run: dotnet test --no-build -c Release
  
  release-nuget:
    name: Release nuget package
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Verify commit exists in origin/master
        run: >
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/* &&
          git branch --remote --contains | grep origin/master
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build project (Release)
        run: dotnet build -c Release
      - name: Pack library
        run: dotnet pack -c Release --output . /p:Version=${VERSION}      
      - name: Push to nuget.org
        run: dotnet nuget push DataflowBuilder.${VERSION}.nupkg --source $NUGET_SOURCE --api-key $API_KEY
        env:
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
          API_KEY: ${{ secrets.NUGET_API_KEY }}
